import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core"
import { Notifications } from '@mantine/notifications'
import type { Metadata } from "next"

import "./globals.css"
import '@mantine/notifications/styles.css'
import { ModalsProvider } from "@mantine/modals"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="es" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="antialiased">
        <MantineProvider >
          <Notifications />
          <ModalsProvider>
            {children}
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
